services:
  web:
    build: .
    container_name: apimex_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/var/www/html/logs
      - ./src/Documents:/var/www/html/src/Documents
      - ./certs:/etc/letsencrypt    # certificados SSL
    depends_on:
      - db
    networks:
      - apimex_network
    network_mode: host

  db:
    image: mysql:8.0
    container_name: firmavirtual_apimex
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./resources/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - apimex_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - apimex_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/apimex/public --quiet && docker exec apimex_app apachectl -k graceful; sleep 12h; done"
    networks:
      - apimex_network

networks:
  apimex_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
